# Generated by Django 2.2 on 2019-05-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_requisito', models.DateTimeField()),
                ('status', models.CharField(choices=[('E', 'Espera'), ('R', 'Recusado'), ('A', 'Aprovado')], max_length=1)),
                ('usuario_dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono', to='mostrar.Usuario')),
                ('usuario_interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessado', to='mostrar.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('L', 'Livros'), ('B', 'Brinquedos'), ('R', 'Roupas'), ('O', 'Outros')], max_length=1)),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.TextField()),
                ('usuario_dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mostrar.Usuario')),
            ],
        ),
    ]
