# Generated by Django 2.2.1 on 2019-05-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='objeto_solicitado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mostrar.Objeto'),
            preserve_default=False,
        ),
    ]
