# Generated by Django 2.2.1 on 2019-06-03 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0002_pedido_objeto_solicitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='usuario_dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario_dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario_interessado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessado', to=settings.AUTH_USER_MODEL),
        ),
    ]
