# Generated by Django 2.2.1 on 2019-06-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0005_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagem',
        ),
    ]
