# Generated by Django 2.2.1 on 2019-06-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0006_auto_20190606_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
