# Generated by Django 2.2.1 on 2019-06-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0007_objeto_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
