# Generated by Django 2.2.1 on 2019-06-06 18:52

from django.db import migrations, models
import mostrar.models


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0008_delete_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='altura_img',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objeto',
            name='largura_img',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='imagem',
            field=models.ImageField(blank=True, height_field='altura_img', null=True, upload_to=mostrar.models.upload_location, width_field='largura_img'),
        ),
    ]
