# Generated by Django 2.2.1 on 2019-06-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0009_auto_20190606_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='tipo',
            field=models.CharField(choices=[('L', 'Livros'), ('B', 'Brinquedos'), ('R', 'Roupas'), ('O', 'Outros')], max_length=50),
        ),
    ]
