# Generated by Django 2.2.1 on 2019-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0010_auto_20190606_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='objeto',
            name='tipo',
            field=models.CharField(choices=[('L', 'Livros'), ('B', 'Brinquedos'), ('R', 'Roupas'), ('O', 'Outros')], default='O', max_length=2),
        ),
    ]
