# Generated by Django 2.2.1 on 2019-06-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0011_auto_20190614_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='tipo',
            field=models.CharField(choices=[('AN', 'Animais De Estimação'), ('BQ', 'Brinquedos'), ('ED', 'Eletrodomésticos'), ('EL', 'Eletrônicos'), ('FR', 'Ferramentas'), ('IC', 'Itens Para Casa'), ('IM', 'Instrumentos Musicais'), ('JT', 'Jogos de Tabuleiro'), ('LI', 'Livros'), ('ME', 'Material de Estudo'), ('MB', 'Mobília'), ('PC', 'Perfumes e Cosméticos'), ('RV', 'Roupas e Vestuário'), ('SD', 'Saúde e Medicina'), ('JV', 'Videogame'), ('OT', 'Outros')], default='OT', max_length=2),
        ),
    ]
