# Generated by Django 2.2.1 on 2019-06-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0012_auto_20190615_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='cidade',
            field=models.CharField(default='Cidade não especificada', max_length=100),
        ),
    ]
