# Generated by Django 2.2.1 on 2019-06-22 06:11

from django.db import migrations, models
import mostrar.models


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar', '0016_auto_20190619_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=mostrar.models.upload_location),
        ),
    ]
